import type { ReactElement } from 'react';
import type { Portals, IdCache, PortalAnchorsIds } from '@pastweb/tools';
import type { ReactEntry } from '../../createEntry';

/**
 * Options used by {@link installPortals}.
 */
export interface PortalsOptions {
  /** Anchor ids generated by `generateAnchors` or a compatible object. */
  anchorsIds: PortalAnchorsIds;
  /**
   * Creates the React entry used by each portal when content is opened.
   *
   * @example
   * ```tsx
   * const portals = installPortals({
   *   anchorsIds,
   *   getEntry: (props, component) => createEntry({ entry: () => component }),
   * });
   * ```
   */
  getEntry: (props: Record<string, any>, component: ReactElement | null) => ReactEntry;
  /** Optional id cache shared with the tools portal layer. */
  idChahe?: IdCache;
  /** Optional portal entry cache shared with the tools portal layer. */
  portalsCache?: Portals;
};
